- credsweeper/__main__.py
- credsweeper/app.py
- credsweeper/ml_model/ml_validator.py
- tests/test_app.py
This PR make ML model work in parallel on few samples 
Speedup is bigger for bigger repos
Command|time before|time after
----|----|----
`python -m credsweeper --path tests/samples/ -j 16 --ml_validation` |0.9s|0.71s
`python -m credsweeper --path CredData/data/387016a6/ -j 16 --ml_validation` |4.8s|1.6s
This PR also adds value to checks in `tests/test_app.py`, as value outputted after #3
> Add batching for ML model inference

- doc/overall_architecture.md
There was wrong file links on `doc/overall_architecture.md` file not only 1.
It was found by @gy741 on #6.
> Fix wrong link 2

- README.md
- credsweeper/app.py
- credsweeper/credentials/line_data.py
- requirements.txt
- setup.py
- tests/test_app.py
Add comment for users who only want to use basic features not Ml validation feature.
> Modify Via git clone (dev install)

- credsweeper/common/constants.py
- credsweeper/rules/config.yaml
- tests/rules/test_aws_s3.py
Hello,
There are two changes.
1. Added info to severity.
2. Added AWS S3 detection rule.
Firebase and S3 do not discover vulnerabilities by exposure alone. Further analysis and vulnerabilities are required. Access control problem.
So I added and changed ```info```.
Thanks.
```
hack@hack:~/CredSweeper$ python3 -m credsweeper --rules credsweeper/rules/config.yaml --path ./strings.txt 
rule: AWS S3 Bucket / severity: info / line_data_list: [line: 'storage.lol.com.s3.amazonaws.com' / line_num: 1 / path: ./strings.txt / value: 'storage.lol.com.s3.amazonaws.com' / entropy_validation: True] / api_validation: NOT_AVAILABLE / ml_validation: NOT_AVAILABLE
rule: AWS S3 Bucket / severity: info / line_data_list: [line: 'storage.lol.com.s3-website.ap-south-1.amazonaws.com' / line_num: 2 / path: …
```
> Add AWS S3 detection rule

- README.md
- setup.py
Changes:
- Add full link to the logo in readme. This allows to see logo on external sites that would copy a readme 
- Update installation section in the `README.md`
- Change name in `setup.py` to lowercase
- Add urls to `setup.py`
- Add classifiers to `setup.py`. Classifiers is searchable tags on the PyPi https://pypi.org/classifiers/
Example of how it would look like after the publication on pypi:
https://test.pypi.org/project/credsweeper/
> Updates for pypi

- README.md
Fix urls due to doc -> docs rename with #29
> Fix urls due to doc -> docs rename

- credsweeper/file_handler/content_provider.py
- credsweeper/file_handler/patch_provider.py
- credsweeper/file_handler/text_content_provider.py
- credsweeper/utils/util.py
- tests/file_handler/test_patch_provider.py
- tests/file_handler/test_text_content_provider.py
Update file content read. Combine patch file reading and full-text file reading
> Update read file content function

- setup.py
Update CredSweeper to version 1.1.0 to indicate changes done in the last month
> Update to 1.1.0

- .pre-commit-config.yaml
- credsweeper/scanner/scan_type/pem_key_pattern.py
- credsweeper/utils/util.py
Add pre-commit hook to analyze python docstring for google python style compliance
> Add pydocstyle hook

- credsweeper/app.py
- credsweeper/common/constants.py
- credsweeper/credentials/credential_manager.py
- credsweeper/credentials/line_data.py
- credsweeper/file_handler/diff_content_provider.py
- credsweeper/file_handler/files_provider.py
- credsweeper/file_handler/patch_provider.py
- credsweeper/file_handler/text_content_provider.py
- credsweeper/file_handler/text_provider.py
- credsweeper/ml_model/features.py
- credsweeper/rules/rule.py
- credsweeper/scanner/scan_type/multi_pattern.py
- credsweeper/scanner/scan_type/pem_key_pattern.py
- credsweeper/scanner/scan_type/scan_type.py
- credsweeper/scanner/scan_type/single_pattern.py
- credsweeper/scanner/scanner.py
Replace Attributes with Parameters according to Sphinx rules.
Compare: 
Old:
[CredSweeper](https://credsweeper.readthedocs.io/en/latest/credsweeper.html#credsweeper.app.CredSweeper)
[ml_model.features.RenyiEntropy](https://credsweeper.readthedocs.io/en/latest/ml_model.html#credsweeper.ml_model.features.RenyiEntropy)
[constants.Chars](https://credsweeper.readthedocs.io/en/latest/common.html#credsweeper.common.constants.Chars)
[CredentialManager](https://credsweeper.readthedocs.io/en/latest/credentials.html#credsweeper.credentials.credential_manager.CredentialManager)
[LineData](https://credsweeper.readthedocs.io/en/latest/credentials.html#credsweeper.credentials.line_data.LineData)
[Rule](https://credsweeper.readthedocs.io/en/latest/rules.html#credsweeper.rules.rule.Rule) …
> Replace Attributes with Parameters

- docs/source/conf.py
- setup.py
Update to setup and doc generator to 1.2.1 for hotfix related to #72
> Update to 1.2.1

- .github/workflows/test.yml
Added scheduled task to test workflow
> Sheduled build

- .flake8
- .github/workflows/test.yml
- credsweeper/common/constants.py
- credsweeper/file_handler/text_content_provider.py
- credsweeper/ml_model/ml_validator.py
- credsweeper/scanner/scan_type/scan_type.py
- credsweeper/scanner/scanner.py
- credsweeper/validations/apply_validation.py
Added flake8 checker to CI workflow
Fixed flake8 issues
> Integrated .flake8 checker

- credsweeper/scanner/scan_type/multi_pattern.py
- credsweeper/scanner/scan_type/pem_key_pattern.py
- credsweeper/scanner/scan_type/scan_type.py
- credsweeper/scanner/scan_type/single_pattern.py
- credsweeper/utils/util.py
Fixed pylint issue "Dangerous default value"
Duplicate code optimized
> Fix suggestions and avoid extra duplicate code

- credsweeper/ml_model/ml_validator.py
Fuzzing takes too much time for instrumental unused tensorflow and numpy.
Fix naming and imports issues.
> Wrap imports to use in fuzzing without tensorflow

- requirements.txt
> Updated requirements.txt to decrease vulnerabilities issues

- .github/workflows/pypi.yml
Added automatic publishing of CredSweeper to PYPI, when new release created.
> Add pypi publish configuration file

- .github/workflows/test.yml
- tests/conftest.py
- tests/rules/common.py
- tests/test_app.py
- tests/test_main.py
Separate application tests and unit-tests
Skip additional filter for UT
> UnitTest enchancement

- docs/source/overall_architecture.rst
Hi, I fixed broken links in the document `overall_architecture`.
> [Doc] Fix broken links in document

- credsweeper/common/keyword_checklist.py
- credsweeper/file_handler/diff_content_provider.py
- credsweeper/utils/__init__.py
- credsweeper/utils/util.py
There are a lot of `mypy` type errors in the source codes.
I fixed incorrect type declarations in util.
> Fix incorrect type declarations in util

- credsweeper/file_handler/file_path_extractor.py
- credsweeper/secret/config.json
- tests/file_handler/test_file_path_extractor.py
- tests/file_handler/test_text_provider.py
- tests/test_app.py
- tests/test_main.py
Windows style directory separator case did not resolved to exclude them.
File path are checked in lowercase
Unit tests and application tests were added
> Bugfix and improvements

- docs/source/conf.py
- setup.py
Update version to perform a new release
Changes for the last few months that will be covered by a release:
- change TF to ONNX for faster runtime https://github.com/Samsung/CredSweeper/pull/96
- change default number of threads to 1 https://github.com/Samsung/CredSweeper/pull/83
- optional find files by extension https://github.com/Samsung/CredSweeper/pull/101
- modified JWT pattern to improve metrics https://github.com/Samsung/CredSweeper/pull/104
- style fixes, type fixes, duplicate code removal
> Update version 1.3.0

- credsweeper/app.py
Speedup when Credsweeper object is created and used many times with ml_validation - skip multiple model load
> MlValidator object is created once

- .github/workflows/test.yml
- setup.py
Credsweeper is installed as utility in system (or virtual environment) additionally with 
```
pip install credsweeper
```
then it might be launched in console like
```
$ credsweeper --path .
```
> Install credsweeper as cli tool additionally

- .github/workflows/fuzz.yml
- .github/workflows/test.yml
- Dockerfile
- action.yml
- entrypoint.sh
- added files to use the project as step in github workflow as [Docker container action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action)
- test in #121 
- refactored workflows code
- TODO: rename 'build' to 'test' in requires checks
> Using CredSweeper as github action

- .github/workflows/action.yml
ActionTest / ActionTest (pull_request) Successful in 53s  - as result 
CredSweeper checks by self:
```
- name: CredSweeper test
uses: Samsung/CredSweeper@main
with:
args: --path ./tests/samples/ --save-json --ml_validation
```
> Test for github action of CredSweeper

- .github/workflows/vcs.yml
> Fix git workflow issue

- credsweeper/__init__.py
Changes:
- size_limit option to skip scan oversize files.
- ML Validator  is created once to avoid extra ml model loading
- Added github action to scan in workflow
> Version up to v1.3.1

- .github/workflows/check.yml
- .github/workflows/pypi.yml
- used 'hexdump' tool instead python to simplify workflow
- fix sphinx build with install all packages
- enable pypi workflow for PR but without publishing
> Fix sphinx documentation workflow

- credsweeper/validations/slack_token_validation.py
- tests/validation/test_validation.py
Uncaught exception might be happen in case wrong server response.
> Bugfix SLACK api validation

- cicd/missed_docstrings.txt
- credsweeper/app.py
- credsweeper/common/constants.py
- credsweeper/credentials/candidate.py
- credsweeper/utils/util.py
- tests/__init__.py
- tests/ml_model/test_features.py
- tests/samples/dummy.key
- tests/test_app.py
- tests/test_main.py
- tests/utils/test_util.py
Some refactoring and tests to reduce next PR ( #153 ) complexity
> Refactoring and unit tests

- credsweeper/__init__.py
> Version up 1.4.0

- .readthedocs.yml
- docs/source/conf.py
- docs/source/guide.rst
- docs/source/overall_architecture.rst
There was no description of [config.json](https://github.com/Samsung/CredSweeper/blob/main/credsweeper/secret/config.json).
So I added description to it and clean documents.
> Add description of config.json and clean documents

- credsweeper/__init__.py
> Version up 1.4.1

- .readthedocs.yml
- README.md
There was no config section on `Readme`, so I added config section for better user experience.
Some users will want to modify the config quickly and it may help them.
> Add config section to readme

- tests/conftest.py
- tests/test_app.py
- tests/test_main.py
- reform lines to fit yapf style and pycharm formatter
- split multi line expected text for convenience debug in future
- added separators in huge test files
> Auxiliary changes for tests

- docs/source/guide.rst
- update list of available arguments on the guide page
- add more details on ML threshold and how to turn it off
- add more details on api validation 
How it will look:
> 2022 Aug 04 guide update

- credsweeper/ml_model/ml_validator.py
- setup.py
Removed obsolete reference to unused file
> Removed reference about char_to_index.pkl

- README.md
- docs/source/develop.rst
- docs/source/guide.rst
- docs/source/index.rst
There are people who confuse tests with running tests.
So create Develop section and move Tests and Benchmark section.
> Move Tests and Benchmark section to Develop section

- credsweeper/__main__.py
- credsweeper/app.py
- requirements.txt
- tests/test_app.py
- tests/validation/test_square_client_id_validation.py
There was no completion phrase, and some users wondered the scanning finished well.
So I added completion phrase at the end of scanning process.
> Add completion phrase

- requirements.txt
There was a alert from dependantbot, so update the numpy version to 1.23.0.
https://github.com/Samsung/CredSweeper/security/dependabot/3
> Update numpy version to 1.23.0

- credsweeper/__init__.py
> Version up 1.4.2

- credsweeper/__main__.py
- credsweeper/app.py
- docs/source/guide.rst
- tests/test_app.py
- tests/test_main.py
- tests/utils/test_util.py
- export default config to file. User might change the config.
- use custom config from user path
- tests
MERGE AFTER #187 
concerning #69
> Custom config for CredSweeper

- .github/workflows/benchmark.yml
Please include a summary of the change and which is is fixed.
- Store result of credsweeper (output.json) as artifact to research in troubleshooting.
- Used sorting of scores to keep order of lines in various environments.
> Benchmark workflow enchancement

- tests/test_main.py
- Fix Unit test due mocking fails randomly
> Refactored unit test to avoid undefined behaviour

- credsweeper/__init__.py
It is time to upgrade the version to v1.4.3
> Version up 1.4.3

- credsweeper/__init__.py
Current code will "rotten" on 14.12.2022. It requires new release.
- Version up to 1.4.6
> Version up to 1.4.6

- SECURITY.md
Adds a link to the issues page.
> Update SECURITY.md to include a link to the issues page

- .github/workflows/benchmark.yml
- .github/workflows/check.yml
- .github/workflows/fuzz.yml
- .github/workflows/pypi.yml
- .github/workflows/test.yml
- README.md
- credsweeper/config/config.py
- credsweeper/file_handler/byte_content_provider.py
- credsweeper/file_handler/content_provider.py
- credsweeper/file_handler/data_content_provider.py
- credsweeper/file_handler/diff_content_provider.py
- credsweeper/file_handler/string_content_provider.py
- credsweeper/file_handler/struct_content_provider.py
- credsweeper/filters/line_specific_key_check.py
- credsweeper/filters/value_allowlist_check.py
- credsweeper/filters/value_first_word_check.py
- credsweeper/filters/value_last_word_check.py
- credsweeper/filters/value_not_allowed_pattern_check.py
- credsweeper/filters/value_useless_word_check.py
- credsweeper/filters/variable_not_allowed_pattern_check.py
- credsweeper/utils/util.py
- docs/source/install.rst
- requirements.txt
- setup.py
- tests/test_app.py
- tests/test_main.py
- tests/utils/test_util.py
- skip Python3.7 support due [pandas source does not support it](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#python-version-support) 
- added used package to requirements explicitly 
- refactoring to reduce cyclomatic complexity
- prepare for support binary diffs after https://github.com/cscorley/whatthepatch/pull/53
> Drop python3.7 support. Refactoring

- SECURITY.md
- credsweeper/__init__.py
- credsweeper/scanner/scan_type/pem_key_pattern.py
- Version up to 1.4.7
- Propose to apply after #246
> Version up to 1.4.7

- README.md
Update `README.md `with link to "issues"
Previewing `README.md`
I clicked the preview button whilst editing the file.
> Update README.md with link to "issues"

- credsweeper/common/constants.py
- tests/common/test_enum.py
- Add comparison operator __lt__ for Severity
> Implement operator __lt__ for Severity

- .github/workflows/pypi.yml
Reverts Samsung/CredSweeper#259
This feature needs more development and it will be merged on future with other PR.
> Revert "Add SLSA Release step in pypi.yml"

- credsweeper/app.py
- credsweeper/file_handler/data_content_provider.py
- fuzz/__main__.py
- tests/samples/sample.py
- Added limits for data which might be represented for deep scan
- Fix UTF-8 surrogates issue during encoding
> Optimization

- credsweeper/file_handler/data_content_provider.py
- credsweeper/utils/util.py
- tests/file_handler/test_data_content_provider.py
- tests/test_app.py
- tests/test_main.py
- tests/utils/test_util.py
- tests/validation/test_github_token_validation.py
- tests/validation/test_google_api_key_validation.py
- tests/validation/test_google_multi_validation.py
- tests/validation/test_mailchimp_key_validation.py
- tests/validation/test_slack_token_validation.py
- tests/validation/test_square_access_token_validation.py
- tests/validation/test_square_client_id_validation.py
- tests/validation/test_stripe_api_key_validation.py
- Add negative tests
- Fix XML wrong recognition for whitespace ending data
- mock validation tests due network problem was caught
> Bugfix and optimization

- requirements.txt
- setup.py
onnxruntime v1.14.0 [issue](https://github.com/microsoft/onnxruntime/issues/14663#issuecomment-1447363017) has vanished 
benchmark scores should be fixed in other PR
> Onnxruntime v1.14.1

- credsweeper/deep_scanner/abstract_scanner.py
- credsweeper/file_handler/content_provider.py
> Removed deprecated @abstractproperty

- .flake8
- .github/workflows/check.yml
- credsweeper/__main__.py
- credsweeper/app.py
- credsweeper/app_path.py
- credsweeper/common/__init__.py
- credsweeper/common/keyword_checklist.py
- credsweeper/credentials/line_data.py
- credsweeper/file_handler/data_content_provider.py
- credsweeper/file_handler/file_path_extractor.py
- credsweeper/filters/value_dictionary_keyword_check.py
- credsweeper/filters/value_file_path_check.py
- credsweeper/filters/value_split_keyword_check.py
- credsweeper/logger/logger.py
- credsweeper/ml_model/features.py
- credsweeper/rules/rule.py
- credsweeper/scanner/scan_type/pem_key_pattern.py
- credsweeper/scanner/scanner.py
- credsweeper/utils/util.py
- tests/__init__.py
- tests/common/test_keyword_checklist.py
- tests/config/test_config.py
- tests/conftest.py
- tests/ml_model/test_features.py
- tests/ml_model/test_ml_validator.py
- tests/test_app.py
- tests/test_main.py
- tests/test_utils/dummy_line_data.py
- Replace any() and all() builtins to plain for ... - it speedups performance in multiple invocations. Probably due context is not switched.
> Performance optimization

- credsweeper/common/constants.py
- credsweeper/filters/group/credit_card_number_sequence.py
- credsweeper/filters/group/pem_pattern.py
- credsweeper/filters/group/url_credentials_group.py
- credsweeper/utils/util.py
- Add DEFAULT for GroupType to apply empty filter set (else branch)
> DEFAULT GroupType

- .github/workflows/benchmark.yml
- Fix artifact upload during benchmark
> benchmark report fix

- credsweeper/ml_model/ml_validator.py
- Fix extra memory consumption
> Reduce memory consuption during ML grouping

- .github/workflows/benchmark.yml
- credsweeper/rules/config.yaml
- tests/__init__.py
- tests/data/depth_9.json
- tests/data/doc.json
- tests/data/output.json
- tests/samples/dropbox_api_secret_long_term
- Add Dropbox API secret (long term) pattern and sample
- [CI] Suppress output during performance benchmark
> Dropbox api

- credsweeper/filters/value_structured_token_check.py
- credsweeper/rules/config.yaml
- tests/__init__.py
- tests/data/depth_9.json
- tests/data/doc.json
- tests/data/output.json
- tests/filters/test_value_structured_token_check.py
- tests/samples/bitbucket_app_password
- Add Bitbucket app password pattern, filter and sample
> Bitbucket app password

- .github/workflows/benchmark.yml
- credsweeper/__main__.py
- credsweeper/app.py
- Add logging initializing for multiple job - then it helps apply configured log level to sub processes
> log level is applied for multiprocess

- credsweeper/rules/config.yaml
- tests/rules/test_telegram_bot_api_token.py
- tests/rules/test_url_credentials.py
- New version of YAPF changed the format. Applied for old version too.
- Fix min rule length of #308 
> YAPF 0.40.0 fix

- .github/workflows/check.yml
- requirements.txt
- Update obviously requirements (latest are installed via setup.py)
- Add SECURITY.md version check for actual credsweeper version
> Update obviously requirements (onnxruntime 1.15)

- credsweeper/__main__.py
- credsweeper/app.py
- docs/source/guide.rst
- tests/test_app.py
- tests/test_main.py
- ``--sort`` is used to obtain sorted output data with constant order. It helps to investigate a difference during development.
> Added option for output sorting

- credsweeper/deep_scanner/deep_scanner.py
- requirements.txt
- tests/__init__.py
- tests/data/depth_3.json
- tests/samples/key_value.json
- When structure has fields "key" and "value" - they values are combined for next analysis
- Use ".toml" extension for increase ML probability
- Update to latest requirements
> Deep analysis update

- .github/workflows/check.yml
- .github/workflows/pypi.yml
- docs/requirements.txt
- docs/source/filters.group.rst
- docs/source/guide.rst
- Fix doc generation issue
- Enable the doc generation test in each PR
> Sphinx issue fix

- credsweeper/rules/config.yaml
- requirements.txt
- tests/samples/url_cred
- Updated versions of librarires
- Fix rule "URL Credentials" to avoid whitespaces in string
> Fixes "URL Credentials"

- credsweeper/__init__.py
- Version UP
- check after release
> Version up to v1.5.3

- cicd/benchmark.txt
- credsweeper/rules/config.yaml
- tests/file_handler/test_text_content_provider.py
- tests/samples/password.gradle
- Add quotes for ``required_regex`` to apply in future pipe sign ``|``
- Fix Password rule and reduced false positives for 3 credentials. Internal experience
> Rules improvement

- .github/pull-request-template.md
- credsweeper/filters/__init__.py
- credsweeper/filters/value_card_number_check.py
- credsweeper/rules/config.yaml
- docs/source/credsweeper.file_handler.rst
- docs/source/credsweeper.filters.rst
- tests/filters/test_value_card_number_check.py
- renamed filter name according with common paradigm
- proposed template changes
> RENAMING: value card number check

- credsweeper/__init__.py
- credsweeper/rules/config.yaml
- tests/__init__.py
- tests/data/doc.json
- tests/test_main.py
remove Password rule from --doc
- Version UP
- Removed password from --doc option
> Version up to 1.5.4

- README.md
Update report sample format in README.md
> Update report sample format in README.md

- credsweeper/common/constants.py
- credsweeper/file_handler/data_content_provider.py
- credsweeper/rules/config.yaml
- credsweeper/rules/rule.py
- credsweeper/scanner/scan_type/multi_pattern.py
- credsweeper/scanner/scan_type/pem_key_pattern.py
- credsweeper/scanner/scanner.py
- docs/source/guide.rst
- tests/rules/test_rule.py
- tests/scanner/scan_type/test_multipattern.py
- Separated old multi_pattern to dedicated "multi"
- fix unused "else" in loop
> Refactored rule type - separated "multi" type

- credsweeper/__main__.py
- docs/source/guide.rst
- tests/test_app.py
- Add ``--no-filter`` argument for CLI
> Argument --no-filters for CLI

- .github/workflows/benchmark.yml
- cicd/benchmark.txt
DONE: fix custom branch for benchmark workflow. merge after https://github.com/Samsung/CredData/pull/39
- Applied tabulated results for benchmark
> Tabulated benchmark result

- credsweeper/deep_scanner/deep_scanner.py
- credsweeper/file_handler/analysis_target.py
- credsweeper/filters/value_ip_check.py
- credsweeper/rules/rule.py
- credsweeper/scanner/scan_type/pem_key_pattern.py
- credsweeper/scanner/scan_type/scan_type.py
- credsweeper/scanner/scanner.py
- Add cached property for Target and optimized using the properties
- Use set() for rules. required_substrings to avoid extra transformations in future
> Optimizations

- README.md
- Fix branch for default code coverage visualisation
> codecov - fix branch

- credsweeper/app.py
- credsweeper/deep_scanner/deep_scanner.py
- credsweeper/utils/util.py
- requirements.txt
- setup.py
- tests/test_main.py
- Optimize ML validator creation - might help in multijob usage, e.g. #424
- Reorganize parent classes in DeepScanner to add new scanners in separated lines and reduce possible conflicts
- optimize file signature detection: startswith instead each element comparison
> Slight changes for development

- README.md
- docs/source/guide.rst
Update the response example of the found credential
> Update Readme and docs

- credsweeper/__init__.py
- Version is increased for release
> Version up to 1.5.10

- credsweeper/app.py
- credsweeper/credentials/candidate.py
- tests/data/depth_3.json
- tests/data/doc.json
- tests/data/ml_threshold_0.json
- tests/data/output.json
- tests/test_main.py
- Use value_start in sorting to prevent variouos order in tests
- Round ml_probability to 5 digits in test and the sort like previous applied
> Use value offset in report sorting

- credsweeper/rules/config.yaml
- tests/__init__.py
- tests/data/doc.json
- disable rule "JSON Web Token" for --doc option 
> disable rule "JSON Web Token" for --doc option

- cicd/benchmark.txt
> Update benchmark scores

- .github/workflows/action.yml
- .github/workflows/benchmark.yml
- .github/workflows/check.yml
- .github/workflows/fuzz.yml
- .github/workflows/pypi.yml
- .github/workflows/rottenness.yml
- .github/workflows/test.yml
- https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> GitHub actions update @v3 -> @v4

- cicd/benchmark.txt
- credsweeper/rules/config.yaml
- tests/__init__.py
- tests/data/__init__.py
- tests/data/depth_3.json
- tests/data/ml_threshold.json
- tests/data/output.json
- tests/samples/url_cred
- tests/samples/url_cred.js
- Fix URL password detection (missed quotation group in regex)
> fix URL password detection

- credsweeper/rules/config.yaml
- tests/data/depth_3.json
- tests/data/doc.json
- tests/data/ml_threshold.json
- tests/data/output.json
- tests/rules/test_slack_webhook.py
- tests/samples/slack_webhook.template
- Fix slack webhook pattern with extended IDs
> slack webhook pattern update

- .github/workflows/benchmark.yml
- cicd/benchmark.txt
- credsweeper/rules/config.yaml
- tests/__init__.py
- tests/data/depth_3.json
- tests/data/doc.json
- tests/data/ml_threshold.json
- tests/data/output.json
- tests/samples/swmtkn
- Add new pattern https://docs.docker.com/reference/cli/docker/swarm/join-token/
- BM scores fix (run_doc_benchmark fails anyway)
> Docker swarm token pattern

- .github/workflows/pypi.yml
- Remove SLSA from publish workflow
> Remove SLSA

- .github/workflows/pypi.yml
- pyproject.toml
- requirements.txt
> Release fix

- README.md
- credsweeper/__init__.py
- openssf score badge add to main README
- version up for #570 #571 release
> Version UP

- credsweeper/credentials/candidate.py
- credsweeper/credentials/line_data.py
- credsweeper/deep_scanner/bzip2_scanner.py
- credsweeper/deep_scanner/deep_scanner.py
- credsweeper/deep_scanner/gzip_scanner.py
- credsweeper/filters/value_entropy_base32_check.py
- credsweeper/filters/value_entropy_base36_check.py
- credsweeper/filters/value_entropy_base64_check.py
- credsweeper/filters/value_not_allowed_pattern_check.py
- credsweeper/filters/value_not_part_encoded_check.py
- credsweeper/filters/value_token_base32_check.py
- credsweeper/filters/value_token_base36_check.py
- credsweeper/filters/value_token_base64_check.py
- credsweeper/filters/variable_not_allowed_pattern_check.py
- tests/data/depth_3.json
- tests/test_main.py
- Code refactored to reduce DC anf EFM 
- Fix possible issues in windows OS with path - applied posix format
- Unified str representation for line_data and candidates
> Code enchancement

- .github/workflows/benchmark.yml
- Add trigger for main push event for DOC BM
> DOC BenchMark workflow

- .github/workflows/action.yml
- .github/workflows/benchmark.yml
- .github/workflows/check.yml
- .github/workflows/fuzz.yml
- .github/workflows/pypi.yml
- .github/workflows/rottenness.yml
- .github/workflows/test.yml
- Dockerfile
* [StepSecurity] Apply security best practices
* Delete .github/dependabot.yml
* Delete .github/workflows/codeql.yml
* Delete .github/workflows/dependency-review.yml
* Delete .github/workflows/scorecards.yml
* Delete .pre-commit-config.yaml
---------
- Add harden runner
> [StepSecurity] Apply security best practices (#42)

- credsweeper/__init__.py
> Version UP to 1.9.3

- .readthedocs.yml
- Fix version of python and system
> ReadTheDocs fix

- .github/workflows/check.yml
- .github/workflows/pypi.yml
- pyproject.toml
- requirements.txt
- try to use newest action release
> Update pypa/gh-action-pypi-publish action

- .github/workflows/pypi.yml
> Avoid install fail

- credsweeper/deep_scanner/deep_scanner.py
- credsweeper/utils/util.py
- tests/utils/test_util.py
- Partially HTML data (<body> only e.g.) is detected with common known tags
> xml detect enchancement

- tests/__init__.py
- tests/data/depth_3.json
- tests/data/doc.json
- tests/data/ml_threshold.json
- tests/data/output.json
- tests/samples/aws_multi.json
> AWS Multi sample update

- requirements.txt
> Bump packages versions

- .github/workflows/action.yml
- action.yml
- Fix codescan issue
- All TODOs will be fixed in next PR (keep in thit for PoC)
> CI warning fix

- .github/workflows/check.yml
- docs/source/credsweeper.deep_scanner.rst
- docs/source/credsweeper.filters.rst
- Add CI documentation check
- Update the documentation with new classes
> [CI] Update documentation check
