Samsung/CredSweeper

setup.py
Limit TF version by <2.6.0
TF 2.6.x contain a newly released bug that will crush program on importing `keras.models`
https://forums.developer.nvidia.com/t/unable-to-import-keras-models-on-tensorflow-2-6-0-jetpack-v46/191904
Code:
`from tensorflow.keras.models import load_model`
Error:
```
credsweeper/ml_model/ml_validator.py:9: in <module>
from tensorflow.keras.models import load_model
...
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
```
=> Limit TF version by <2.6.0

.github/CODEOWNERS, README.md
Modify `CODEOWNERS` to use github teams to modify code owners more easily.
=> Update CODEOWNERS to use github teams

doc/overall_architecture.md
There was a wrong file link on `doc/overall_architecture.md` file.
It was found by @gy741 on #6.
=> Fix wrong link

credsweeper/rules/config.yaml, tests/rules/test_firebase_domain.py
Hello,
Added Firebase detection rules.
```
hack@hack:~$ cat strings.txt 
<string name="firebase_database_url">https://api-project-615509201123.firebaseio.com</string>
<string name="firebase_database_url">https://api-project-615509201123.firebaseapp.com</string>
```
```
hack@hack:~$ python3 -m credsweeper --path /home/hack/strings.txt --rule /home/hack/config.yaml 
rule: Firebase io Token / severity: high / line_data_list: [line : '    <string name="firebase_database_url">https://api-project-615509201123.firebaseio.com</string>' / line_num : 1 / path : /home/hack/strings.txt / value: 'api-project-615509201123.firebaseio.com' / entropy_validation: True] / api_validation: NOT_AVAILABLE / ml_validation: NOT_AVAILABLE
rule: Firebase APP Token / severity: high / line_data_list: [line : ' …
```
=> Add Firebase rule

.github/workflows/python-package.yml, .github/workflows/test.yml
Add git-hub action for testing cred sweeper
This work will test:
```shell
pip install .
pip install .[ml]
pytest -m pytest -m "not api_validation" tests/
```
On Python: 3.7, 3.8, 3.9
Latest stable Windows, MacOS, Ubuntu
API validation tests omitted so we do not DDOS services from GitHub servers
=> Add test action

setup.py
Allow tensorflow `2.6.2` and `2.7.0` instalstion
Both released 13 days ago: https://github.com/tensorflow/tensorflow/releases
TF `2.6.1` and `2.6.0` still have a bug that brakes `load_model` function
=> Add tensorflow 2.7.0, 2.6.2 support

credsweeper/common/constants.py, credsweeper/file_handler/analysis_target.py, credsweeper/file_handler/diff_content_provider.py, credsweeper/utils/__init__.py, credsweeper/utils/util.py, tests/file_handler/test_diff_content_provider.py, tests/file_handler/test_text_content_provider.py, tests/samples/multiline.patch, tests/test_app.py
Update patch anlisys for support multiline rules. 
Previously row indexes for second line in multiline rule was incorrect.
Also, added test case for multiline rules handling and content providers
=> Update patch anlisys for support multiline rules

credsweeper/credentials/credential_manager.py
Using ML validation for multiline rules leads to duplicate report note for each line data in line_data_list, as below: 
> rule: AWS Client ID / severity: high / line_data_list: [line: ' clid = "AKIAQWADE5R42RDZ4JEM"' / line_num: 4 / path: creds.py / value: 'AKIAQWADE5R42RDZ4JEM' / entropy_validation: False] / api_validation: NOT_AVAILABLE / ml_validation: VALIDATED_KEY
> **rule: AWS Multi / severity: high / line_data_list: [line: ' clid = "AKIAQWADE5R42RDZ4JEM"' / line_num: 4 / path: creds.py / value: 'AKIAQWADE5R42RDZ4JEM' / entropy_validation: False, line: ' token = "V84C7sDU001tFFodKU95USNy97TkqXymnvsFmYhQ"' / line_num: 5 / path: creds.py / value: 'V84C7sDU001tFFodKU95USNy97TkqXymnvsFmYhQ' / entropy_validation: True] / api_validation: NOT_AVAILABLE / ml_validation: VALIDATED_KEY
> …
=> Quick Fix duplicated report note for each element in multiline rule

credsweeper/rules/config.yaml, tests/rules/test_pypi_api_token.py
Related to https://github.com/Samsung/CredSweeper/issues/26
Update pypi regex, as current regex cannot detect some real tokens
- Old regex included `AgEIcHlwaS5vcmc` at the start, which is not always the case for real tokens
- Real tokens can have different lengths
=> Update pypi regex

credsweeper/ml_model/ml_validator.py
Add more meaningful error that will happen in ML libraries not found
Example output:
```
$ python -m credsweeper --path tests/samples/password --ml_validation
Traceback (most recent call last):
File "/home/user/share/code/credsweeper_replicas/meanrin/CredSweeper/credsweeper/ml_model/ml_validator.py", line 9, in <module>
import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/user/share/code/credsweeper_replicas/meanrin/CredSweeper/credsweeper/__main__.py", line 107, in <module>
main() …
```
=> Add ModuleNotFoundError error message about ML

credsweeper/app.py
Fix for #39 
Print result to console only if `--save-json` not selected
=> Suppress CLI out if results saved to json

credsweeper/utils/util.py, tests/file_handler/test_patch_provider.py
Fix for #43 
Change `UnicodeError` related logging to info
=> Less unicode error logging

.style.yapf, credsweeper/__main__.py, credsweeper/app.py, credsweeper/config/config_manager.py, credsweeper/credentials/candidate.py, credsweeper/credentials/candidate_group_generator.py, credsweeper/file_handler/analysis_target.py, credsweeper/file_handler/content_provider.py, credsweeper/file_handler/diff_content_provider.py, credsweeper/file_handler/patch_provider.py, credsweeper/file_handler/text_content_provider.py, credsweeper/file_handler/text_provider.py, credsweeper/filters/group/general_keyword.py, credsweeper/filters/group/general_pattern.py, credsweeper/filters/group/group.py, credsweeper/filters/group/password_keyword.py, credsweeper/filters/group/pem_pattern.py, credsweeper/filters/group/url_credentials_group.py, credsweeper/filters/value_pattern_filter.py, credsweeper/logger/logger.py, credsweeper/ml_model/ml_validator.py, credsweeper/scanner/scan_type/multi_pattern.py, credsweeper/scanner/scan_type/scan_type.py, credsweeper/scanner/scanner.py, credsweeper/utils/util.py, credsweeper/validations/apply_validation.py, credsweeper/validations/validation.py
By the Google style guide it's required to have a blank line between a class declaration and the first function
(with class-docstring): https://google.github.io/styleguide/pyguide.html#384-classes
(no class-docstring): https://google.github.io/styleguide/pyguide.html#3193-forward-declarations 
Black lines between class docsting and fist func was added with https://github.com/Samsung/CredSweeper/pull/49
But yapf config was not updated, so some of this changes might be accidentally reverted back 
This PR changes:
- Update `yapf` config (`blank_line_before_nested_class_or_def`) so it would force an empty line between the class name and first function
- Rerun `yapf` on credsweeper dir
- Rerun `isort` on credsweeper dir
=> Update yapf config, rerun yapf/isort

credsweeper/secret/log.yaml
Fix warning message in tests:
```
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/importlib/_bootstrap.py:219: ResourceWarning: unclosed file <_io.FileIO name='/home/runner/work/CredSweeper/CredSweeper/credsweeper/log/credsweeper.log' mode='ab' closefd=True>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
Fix based on:
https://stackoverflow.com/a/30684667
`delay: True` make that file only created on after at least 1 log message emitted
https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler
`If delay is true, then file opening is deferred until the first call to emit().`
=> Fix ResourceWarning in tests

credsweeper/__main__.py, credsweeper/app.py, credsweeper/common/constants.py, credsweeper/ml_model/ml_validator.py, credsweeper/ml_model/model_config.json, tests/test_app.py
Resolve #42 
Add ML thresholds based on best F-0.25 F-0.5 F-1 F-2 F-4 scores
Set default to medium (best F-1)
----------------
Threshold calculated from train repos in CredData:
```
"lowest": 0.22916731,
"low": 0.3573966,
"medium":  0.62203974,
"high": 0.7979102,
"highest": 0.9299587
```
Current CredSweeper main branch on this thresholds:
Threshold|TP|FP|TN|FN|FPR|FNR|PRC|RCL|F1
-|-|-|-|-|-|-|-|-|-
0.22916731|3851|982|19453717|732|0.00005|0.15972|0.79681|0.84028|0.81797
0.3573966|3807|631|19454068|776|0.00003|0.16932|0.85782|0.83068|0.84403
**0.5 (current default)**|3739|440|19454259|844|0.00002|0.18416|0.89471|0.81584|0.85346
0.62203974|3662|319|19454380|921|0.00002|0.20096|0.91987|0.79904|0.85521
0.7979102|3444|170|19454529|1139|0.00001|0.24853|0.95296|0.75147|0.84031 …
=> Add model threshold

credsweeper/ml_model/features.py
For some numpy.ndarray, the data type "numpy.array"([function](https://numpy.org/doc/stable/reference/generated/numpy.array.html)) was specified.
=> Fix incorrect datatype for np.ndarray objects

credsweeper/common/constants.py, credsweeper/rules/config.yaml, credsweeper/rules/rule.py, credsweeper/scanner/scan_type/scan_type.py, credsweeper/scanner/scanner.py
**Summary**:
- This PR improves execution time 5-7 times (based on repo under a scan) without any change to the output
Current main branch:
```bash
time python -m credsweeper --path CredData/data/ -j 16 --save-json dataset_main.json
real    7m34,493s
user    30m57,242s
sys     0m3,632s
```
With this change:
```bash
$ time python -m credsweeper --path CredData/data/ -j 16 --save-json dataset_fast.json
real    1m23,158s
user    5m16,442s
sys     0m3,064s
```
Output is identical:
```bash
$ cmp --silent dataset_main.json dataset_faster.json && echo '### SUCCESS: Files Are Identical! ###' || echo '### WARNING: Files Are Different! ###'
$ wc -l dataset_main.json && tail -10 dataset_main.json
385218 dataset_main.json
"value": "b03f5f7f11d50a3a",
"variable": "PublicKeyToken", …
```
=> Faster execution based on regex

credsweeper/scanner/scan_type/multi_pattern.py, credsweeper/scanner/scan_type/pem_key_pattern.py, credsweeper/scanner/scan_type/scan_type.py, credsweeper/scanner/scan_type/single_pattern.py
`MAX_LINE_LENGTH` attribute do not exists in files in `credsweeper/scanner/scan_type/`
`MAX_LINE_LENGTH` do exist, but in the constants:
https://github.com/Samsung/CredSweeper/blob/f82629d5c065e34c99f79035db370d566d58204c/credsweeper/common/constants.py#L81
So it's better to remove this attributes from files in `credsweeper/scanner/scan_type/`, as they are providing a false information
=> Remove non-existing attributes from docstring

setup.py
Newly released TF 2.8.0 have a different Keras API
Until new API implemented in the code, this PR limit the TF version to `<2.8.0`
```
$ python -m credsweeper --path tests/samples/password --ml_validation
Traceback (most recent call last):
File "/home/user/share/code/credsweeper_replicas/meanrin/CredSweeper/credsweeper/ml_model/ml_validator.py", line 12, in <module>
from tensorflow.python.keras.preprocessing.sequence import pad_sequences
ModuleNotFoundError: No module named 'tensorflow.python.keras.preprocessing'
```
=> Limit TF version by 2.8.0

credsweeper/__main__.py, credsweeper/app.py, docs/source/guide.rst, docs/source/overall_architecture.rst
Multiple jobs do overhead with creating new processes and not speedup time.
Some tests results:
Start: 1643570067.692241777 Stop: 1643570404.724208434 Elapsed (seconds): 337.031966657
1 jobs calculates lines per second:10349.08657062116809152130
Start with job_cfg='-j 2'
Start: 1643570404.734513404 Stop: 1643570676.303738281 Elapsed (seconds): 271.569224877
2 jobs calculates lines per second:12843.77123946862485045807
Start with job_cfg='-j 4'
Start: 1643570676.315110215 Stop: 1643570905.733240183 Elapsed (seconds): 229.418129968
4 jobs calculates lines per second:15203.56303351663627051851
Start with job_cfg='-j 8'
Start: 1643570905.745620467 Stop: 1643571128.117708713 Elapsed (seconds): 222.372088246
8 jobs calculates lines per second:15685.30037880210985298964
Start with job_cfg='-j …
=> Single job by default

credsweeper/ml_model/ml_validator.py, requirements.txt, setup.py
Related to: https://github.com/Samsung/CredSweeper/pull/72 
Due to the change in keras library location in tf 2.8.0:
- Add if to check tf version
- Add different imports for 2.8 and prior versions
=> Add if to support new keras imports in TF 2.8.0

credsweeper/__main__.py, credsweeper/app.py, credsweeper/config/config.py, credsweeper/config/config_manager.py, credsweeper/file_handler/file_path_extractor.py, credsweeper/secret/config.json, credsweeper/validations/apply_validation.py, tests/conftest.py, tests/file_handler/test_file_path_extractor.py, tests/test_app.py, tests/test_utils/dummy_line_data.py
Add `--find-by-ext` option for key files ( `.pem` , `.crt`, `.cer`,  `.csr`,  `.der`,  `.pfx`,  `.p12`, `.key` and `.jks`). #94 
By default, `--find-by-ext` option is `False`.
It just finding key files by extensions, so there is no `line_data`, `line_num` and so on.
Here is example.
``` json
[
{
"api_validation": "NOT_AVAILABLE",
"ml_validation": "NOT_AVAILABLE",
"line_data_list": [
{
"line": "dummy line",
"line_num": -1,
"path": "key_test/my_key.pem",
"value": null,
"variable": null,
"entropy_validation": false
}
],
"ml_probability": null,
"rule": "Dummy candidate",
"severity": "info"
}
]
```
=> Add find by ext option

credsweeper/__main__.py
I fixed below type hint errors in `__main__.py`
```
credsweeper/__main__.py:32: error: Function "argparse.ArgumentParser.parse_args" is not valid as a type
credsweeper/__main__.py:32: note: Perhaps you need "Callable[...]" or a callback protocol?
credsweeper/__main__.py:118: error: ArgumentParser.parse_args? has no attribute "log"
credsweeper/__main__.py:119: error: ArgumentParser.parse_args? has no attribute "log"
credsweeper/__main__.py:121: error: ArgumentParser.parse_args? has no attribute "path"
credsweeper/__main__.py:122: error: ArgumentParser.parse_args? has no attribute "path"
credsweeper/__main__.py:123: error: ArgumentParser.parse_args? has no attribute "path"
credsweeper/__main__.py:123: error: ArgumentParser.parse_args? has no attribute "skip_ignored" …
```
=> Fix type errors in __main__.py

credsweeper/rules/config.yaml
There were not many JWT cases in perfect form.
So I fixed `JSON Web Token` regex by remove `.eyj` string set and here is result.
I tested with [CredData](https://github.com/Samsung/CredData).
Before:
``` bash
result_cnt : 3981, lost_cnt : 0, true_cnt : 3662, false_cnt : 319
credsweeper -> TP : 3662, FP : 319, TN : 19454380, FN : 921, FPR : 0.0000163971, FNR : 0.2009600698, ACC : 0.9999362772, PRC : 0.9198693796, RCL : 0.7990399302, F1 : 0.8552078468
credsweeper Private Key -> TP : 953, FP : 0, TN : 4, FN : 39, FPR : 0E-10, FNR : 0.0393145161, ACC : 0.9608433735, PRC : 1.0000000000, RCL : 0.9606854839, F1 : 0.9799485861
credsweeper Predefined Pattern -> TP : 273, FP : 2, TN : 40, FN : 54, FPR : 0.0476190476, FNR : 0.1651376147, ACC : 0.8482384824, PRC : 0.9927272727, RCL : 0.8348623853, F1 …
```
=> Fix JSON Web Token regex to reduce FN cases

credsweeper/__main__.py, credsweeper/app.py, credsweeper/config/config.py, credsweeper/scanner/scan_type/scan_type.py, credsweeper/secret/config.json, docs/source/guide.rst, tests/test_app.py, tests/test_main.py
Resolves #195 
- add blacklist field to the default config. Old configs without the fields will still be processed normally
- add separate value and line blacklists. Both ignores space-like characters at left and right
- add blacklist CLI arg that extends the list from config
- at the moment CLI blacklist adds to both line and value blacklist for simplicity and user convenience. However, interface allows to add line and value lists separately 
- blacklist stored as Sets rather than Lists. Sets on average faster for `x in y` checks, and have average search time of O(1) https://wiki.python.org/moin/TimeComplexity 
- update the guide with blacklisting details 
=> Add option to exclude outputs with cli and config

.github/workflows/benchmark.yml, .github/workflows/check.yml, credsweeper/__init__.py, credsweeper/__main__.py, docs/source/guide.rst, fuzz/fuzzing.sh, tests/test_app.py
- Added `--banner` option to distinguish various version in development. CRC32 sum of files might be displayed in banner at program start. ```CredSweeper v1.4.2 crc32:ae1baf99```. It is not an integrity check but fast.
- Use natural order in benchmark first:old, second:new.
=> Banner with version and CRC32 sum of program files

.github/workflows/benchmark.yml
- Fix github workflow 'benchmark' to use current code of CredSweeper. After #212 maybe used --banner to confirm wthat code is used.
=> Modify benchmark workflow to use current code instead cloned

.github/workflows/check.yml, .github/workflows/test.yml, README.md, docs/source/install.rst, setup.py, tests/test_app.py
There is an error in `test_help_p()` method which in `tests/test_app.py` when I trying to run pytest with python3.10.x version.
I investigated the error and I found there is a change on `argparse`.
https://docs.python.org/3/whatsnew/3.10.html#argparse
Following the document ***Misleading phrase “optional arguments” was replaced with “options” in argparse help.*** so I replaced "optional arguemnts" to "options" in `test_help_p()`.
- Fix `test_help_p()` error
=> Fix test help p error

.github/workflows/rottenness.yml
- applied recursive scan for source folder - bugfix of CI workflow
- increased period for obsolete release to 28 days. The PR is pass, but on next Monday (25th) it should fail. Then we do release and then may reduce the period again.
=> Fix github action to check last release

credsweeper/app.py, credsweeper/credentials/candidate.py, credsweeper/credentials/line_data.py, credsweeper/file_handler/analysis_target.py, credsweeper/file_handler/byte_content_provider.py, credsweeper/file_handler/content_provider.py, credsweeper/file_handler/data_content_provider.py, credsweeper/file_handler/diff_content_provider.py, credsweeper/file_handler/string_content_provider.py, credsweeper/file_handler/text_content_provider.py, credsweeper/scanner/scan_type/multi_pattern.py, credsweeper/scanner/scan_type/scan_type.py, credsweeper/secret/config.json, tests/common/test_constants.py, tests/credentials/test_credential_manager.py, tests/credentials/test_line_data.py, tests/file_handler/test_byte_content_provider.py, tests/file_handler/test_diff_content_provider.py, tests/file_handler/test_string_content_provider.py, tests/file_handler/test_text_content_provider.py, tests/ml_model/test_features.py, tests/ml_model/test_ml_validator.py, tests/rules/common.py, tests/rules/test_pem_key.py, tests/rules/test_token.py, tests/test_main.py, tests/test_utils/dummy_line_data.py, tests/utils/test_util.py, tests/validation/test_validation.py
- INFO field was added to inform user which way credentials were found. "Virtual" files in containers cannot be found. 
MERGE AFTER #224
=> Added Info field to json report

credsweeper/file_handler/file_path_extractor.py, credsweeper/file_handler/patch_provider.py, tests/file_handler/test_patch_provider.py
- Use configured param ``size_limit`` in PatchProvider to skip too big diffs which are computed a long time with ``whatthepath``
=> Propagate size limit config to PatchProvider

.github/pull-request-template.md, credsweeper/__init__.py, requirements.txt, tests/test_app.py
fixes #242 
- updated requirement whatthepath to 1.0.3
- Add test for huge diff (git patch) parsing
- version up to 1.4.5
=> Version up to 1.4.5

.github/workflows/pypi.yml
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
- Modified trigger for release - the workflow will run when release issued (not pre-release)
=> Change trigger for release

.github/workflows/pypi.yml
Add SLSA Release step in pypi.yml
SLSA release steps is implemented as reusable-workflow in Samsung/SupplyChainAssurance/.github/workflow/python_releasor.yml
If use it, below files will be uploaded as assets of release
- whl, tar.gz for pypi
- an SBOM(spdx type)
- an Attestation(slsa provenance)
=> Add SLSA Release step in pypi.yml

.github/workflows/pypi.yml
SLSA release steps is implemented as reusable-workflow in Samsung/SupplyChainAssurance/.github/workflow/
If use it, below files will be uploaded as assets of release
- whl, tar.gz for pypi
- an SBOM(spdx type)
- an Attestation(slsa provenance)
This PR is different from e7ca9de10f7cd633d1e71329fb72ace3348891fc
- python_builder worklfow is used instead of python_releasor. 
python_builder workflow runs by pull_request/push/released events
- slsa_release/upload-assets runs only by released events
Check release assets after release
=>  Add SLSA Release step in pypi.yml

.mypy.ini, setup.py
- workaround for issue for macos Python 3.9.16 (pip23) and latest version of onnxruntime v1.14.0
https://github.com/microsoft/onnxruntime/issues/14663
=> onnxruntime fix for Python 3.9.16 in macos

cicd/benchmark.txt, credsweeper/filters/cred_card_number_check.py, credsweeper/filters/group/__init__.py, credsweeper/filters/group/credit_card_number_sequense.py, credsweeper/rules/config.yaml, tests/__init__.py, tests/filters/test_credit_card_number_check.py, tests/samples/credit_card_numbers, tests/test_main.py
- Added rule to find credit card number in number sequnce
- Added filter to check the number sequence with Luhn algorithm
Probably necessary to apply https://github.com/Samsung/CredData/pull/22 first - then update the scores
=> Credit card number rule and filter

credsweeper/file_handler/file_path_extractor.py, tests/file_handler/test_file_path_extractor.py
- Skip scan symlinks in walked directory (obviously given file - is scanned)
=> Skip symlink during files extraction

credsweeper/rules/config.yaml, tests/__init__.py, tests/data/depth_9.json, tests/data/doc.json, tests/data/output.json, tests/test_app.py
- Update Shopify token rule with disabled ml because it has strong prefix signature and ML is overhead for this
=> Shopify token rule updated

credsweeper/file_handler/data_content_provider.py, tests/data/depth_9.json, tests/data/doc.json
- reduced html text without <header>, <body> might be parsed too
- add line end for <p> tags to split values
=> reduced html is parsed too with additional line ending for <p>

credsweeper/file_handler/file_path_extractor.py, tests/file_handler/test_file_path_extractor.py
`FilePathExtractor.check_exclude_file()` method has a bug before.
The method just convert a `path` to lower case, so when checking the exclude file path, it didn't work properly.
I fixed this bug with adding `lower_path` parameter to `check_exclude_file()`.
`check_exclude_file()` uses `lower_path` on pattern matching and uses `path` on excluding exact paths and extensions.
- Fix bug of `check_exclude_file()`
=> Add lower_path to check_exclude_file() for exclude exact file path

credsweeper/rules/config.yaml, tests/__init__.py, tests/data/doc.json
I've checked the results from `--doc` option internally and there are a lot of FPs with `URL Credentials` rule.
So remove `URL Credentials` rule from `--doc` option.
- Remove `URL Credentials` rule from `--doc` option
=> Remove URL Credentials rule from doc option

credsweeper/app.py
- Add log when ml validation is disabled
- skip ml_validator creation when no candidates were found
=> Skip ml_validator creation when no credentials found

credsweeper/filters/__init__.py, credsweeper/filters/value_iban_check.py, credsweeper/rules/config.yaml, requirements.txt, setup.py, tests/__init__.py, tests/data/depth_3.json, tests/data/ml_threshold_0.json, tests/data/output.json, tests/samples/iban, tests/test_app.py
- Add IBAN detection as PII sensetive info and good recognized data
- Slight fixes in heroku rule with deprecation warning
=> IBAN detection

setup.py
There was an error when I trying to use CredSweeper v1.5.6 with bs4 package which version under 4.12.2.
``` bash
ImportError: cannot import name 'XMLParsedAsHTMLWarning' from 'bs4' (/usr/lib/python3/dist-packages/bs4/__init__.py)
```
So I added version ragne to `setup.py` to avoid this error.
- Fix bs4 require version error
=> Add version range to bs4 package

credsweeper/__init__.py
=> version up to 1.5.8

.github/workflows/benchmark.yml
This PR is for process CredData DOC BMT.
CredData DOC BMT is done internally, and just update the commit status when PR timing.
You can check the result through the commit status of b8bdb1a at https://github.com/csh519/CredSweeper/pull/8.
- Add DOC BMT feature
=> Add run_doc_benchmark

credsweeper/credentials/credential_manager.py, credsweeper/scanner/scan_type/scan_type.py
=> warning fix

credsweeper/ml_model/features.py, experiment/requirements.txt, pyproject.toml, requirements.txt
- remove scikit-learn from sources
- migrated to custom binarization - no slowdown, even speedup 2~3%
- add scikit-learn in experiment (ML train requirements)
- partially fixes #568 
=> remove scikit-learn from release installation

credsweeper/utils/util.py, tests/utils/test_util.py
- Detect unprintable bytes during LATIN-1 decoding
=> Improving for binary file detection for latin1

credsweeper/common/keyword_pattern.py, credsweeper/filters/__init__.py, credsweeper/filters/group/password_keyword.py, credsweeper/filters/line_git_binary_check.py, credsweeper/filters/line_uue_part_check.py, credsweeper/rules/config.yaml, tests/__init__.py, tests/data/depth_3.json, tests/data/ml_threshold.json, tests/data/output.json, tests/file_handler/test_data_content_provider.py, tests/filters/test_line_uue_part_check.py, tests/filters/test_value_array_dictionary_check.py, tests/filters/test_value_string_type_check.py, tests/ml_model/test_ml_validator.py, tests/samples/password_FALSE, tests/samples/password_TRUE, tests/test_main.py, tests/utils/test_util.py
- Add LineUUECheck filter
- add the filter to password (PW: - very often appear) and for doc rule
- fix tests
- Excludde ``,`` and ``;`` in unquotted variable for keyword 
=> Filter for line which is UU encoded

credsweeper/file_handler/data_content_provider.py, tests/__init__.py, tests/data/depth_3.json, tests/data/doc.json, tests/samples/table.html, tests/test_main.py
- Refactoring HTML table transformation with appropriated colspan and rowspan
=> Deep scan: html table transformation

credsweeper/__main__.py, credsweeper/app.py, credsweeper/credentials/line_data.py, credsweeper/deep_scanner/gzip_scanner.py, credsweeper/file_handler/diff_content_provider.py, credsweeper/filters/value_camel_case_check.py, credsweeper/filters/value_file_path_check.py, credsweeper/ml_model/features/__init__.py, credsweeper/ml_model/ml_validator.py, docs/source/guide.rst, pyproject.toml, requirements.txt, tests/test_app.py, tests/test_main.py
- Add colorization for stdout to make review credentials more usability
=> Credential colorization in stdout export

.github/workflows/check.yml, pyproject.toml
- Use static version in pyproject.toml for PyPi
- Add check for the versions match
=> Fix build for PyPi

credsweeper/credentials/candidate.py, credsweeper/rules/config.yaml, requirements.txt, tests/data/doc.json, tests/test_doc.py
- Set confidence "weak" for DOC_CREDEENTIALS
- Update requirement GitPython==3.1.44
=> Set 'weak' confidence for DOC_CREDENTIALS rule

.github/workflows/action.yml, .github/workflows/benchmark.yml, .github/workflows/check.yml, .github/workflows/fuzz.yml, .github/workflows/pypi.yml, .github/workflows/rottenness.yml, .github/workflows/test.yml, docs/source/install.rst, pyproject.toml, requirements.txt
- Removed python3.8 checks and package limitations fixes #666 
- Update actions references and yaml format
=> Drop Python 3.8 support

.github/workflows/benchmark.yml, credsweeper/__main__.py, credsweeper/app.py, credsweeper/file_handler/byte_content_provider.py, credsweeper/file_handler/content_provider.py, credsweeper/file_handler/data_content_provider.py, credsweeper/file_handler/diff_content_provider.py, credsweeper/file_handler/string_content_provider.py, credsweeper/file_handler/struct_content_provider.py, credsweeper/file_handler/text_content_provider.py, credsweeper/utils/util.py, docs/source/guide.rst, fuzz/__main__.py, fuzz/coveraging.sh, fuzz/fuzzing.sh, fuzz/minimizing.sh, fuzz/re-fuzzing.sh, fuzz/reducing.sh, tests/data/__init__.py, tests/file_handler/test_byte_content_provider.py, tests/file_handler/test_data_content_provider.py, tests/file_handler/test_diff_content_provider.py, tests/file_handler/test_string_content_provider.py, tests/file_handler/test_struct_content_provider.py, tests/file_handler/test_text_content_provider.py, tests/test_app.py
- Add --thrifty agrument to cleanup unnecessary data after scan to prevent extra memory consumption. IO descriptors are closed also.
- Re-fuzzed with the argument
Before --thrifty (v1.10.4):
```
Detected Credentials: 11731
Time Elapsed: 376.4159982204437s
Command being timed: ".venv/bin/python -m credsweeper --sort --path data --subtext --save-json -j 4 --log info"
User time (seconds): 1420.57
System time (seconds): 5.15
Percent of CPU this job got: 377%
Elapsed (wall clock) time (h:mm:ss or m:ss): 6:17.30
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 1077604
Average resident set size (kbytes): 0
Major …
```
=> Thrifty memory consumption

credsweeper/deep_scanner/mxfile_scanner.py, credsweeper/file_handler/data_content_provider.py, credsweeper/utils/util.py, tests/__init__.py, tests/data/depth_3.json, tests/data/doc.json, tests/data/ml_threshold.json, tests/data/output.json, tests/file_handler/test_data_content_provider.py, tests/samples/pretty.html, tests/samples/test.html, tests/test_main.py
- Use TAB instead LF to add separators in some html tags
- Fix Benchmark scores
=> Prevent extra line split for HTML scan

experiment/main.py, experiment/main.sh, experiment/requirements.txt, experiment/src/lstm_model.py, experiment/src/model_config_preprocess.py, experiment/src/prepare_data.py, experiment/src/strength_test.py
=> Experiment sync
